In [1]:
import pandas as pd
import numpy as np

In [2]:
rs = pd.read_csv("2021-001_Schauberger-et-al_Data_FILTERED/wheat_winter_data_1900-2018_FILTERED.txt", index_col= False, sep = ";")

In [3]:
[[i] for i in (list(rs[rs.department == "Ain"].year))]

[[1900],
 [1901],
 [1902],
 [1903],
 [1904],
 [1905],
 [1906],
 [1907],
 [1908],
 [1909],
 [1910],
 [1911],
 [1912],
 [1913],
 [1914],
 [1915],
 [1916],
 [1917],
 [1918],
 [1919],
 [1920],
 [1921],
 [1922],
 [1923],
 [1924],
 [1925],
 [1926],
 [1927],
 [1928],
 [1929],
 [1930],
 [1931],
 [1932],
 [1933],
 [1934],
 [1935],
 [1936],
 [1937],
 [1938],
 [1939],
 [1940],
 [1941],
 [1942],
 [1943],
 [1944],
 [1945],
 [1946],
 [1947],
 [1948],
 [1949],
 [1950],
 [1951],
 [1952],
 [1953],
 [1954],
 [1955],
 [1956],
 [1957],
 [1958],
 [1959],
 [1960],
 [1961],
 [1962],
 [1963],
 [1964],
 [1965],
 [1966],
 [1967],
 [1968],
 [1969],
 [1970],
 [1971],
 [1972],
 [1973],
 [1974],
 [1975],
 [1976],
 [1977],
 [1978],
 [1979],
 [1980],
 [1981],
 [1982],
 [1983],
 [1984],
 [1985],
 [1986],
 [1987],
 [1988],
 [1989],
 [1990],
 [1991],
 [1992],
 [1993],
 [1994],
 [1995],
 [1996],
 [1997],
 [1998],
 [1999],
 [2000],
 [2001],
 [2002],
 [2003],
 [2004],
 [2005],
 [2006],
 [2007],
 [2008],
 [2009],
 [2010],
 

In [4]:
rs['department'].unique()

array(['Ain', 'Aisne', 'Allier', 'Alpes_de_Haute_Provence',
       'Alpes_Maritimes', 'Ardeche', 'Ardennes', 'Ariege', 'Aube', 'Aude',
       'Aveyron', 'Bas_Rhin', 'Bouches_du_Rhone', 'Calvados', 'Cantal',
       'Charente', 'Charente_Maritime', 'Cher', 'Correze', 'Corse_du_Sud',
       'Cote_d_Or', 'Cotes_d_Armor', 'Creuse', 'Deux_Sevres', 'Dordogne',
       'Doubs', 'Drome', 'Essonne', 'Eure', 'Eure_et_Loir', 'Finistere',
       'Gard', 'Gers', 'Gironde', 'Haut_Rhin', 'Haute_Corse',
       'Haute_Garonne', 'Haute_Loire', 'Haute_Marne', 'Haute_Saone',
       'Haute_Savoie', 'Haute_Vienne', 'Hautes_Alpes', 'Hautes_pyrenees',
       'Hauts_de_Seine', 'Herault', 'Ille_et_Vilaine', 'Indre',
       'Indre_et_Loire', 'Isere', 'Jura', 'Landes', 'Loir_et_Cher',
       'Loire', 'Loire_Atlantique', 'Loiret', 'Lot', 'Lot_et_Garonne',
       'Lozere', 'Maine_et_Loire', 'Manche', 'Marne', 'Mayenne',
       'Meurthe_et_Moselle', 'Meuse', 'Morbihan', 'Moselle', 'Nievre',
       'Nord', 'Oise', 'Orn

In [5]:
rs = rs[rs['year'] > 2002]
rs = rs.dropna()

In [6]:
rs["Div"] = rs.production / 10000

In [8]:
for i in rs["Div"]:
    print(i)

103      12.73113
104      22.82640
105      18.38652
106      22.71960
107      19.88030
           ...   
11531    29.54800
11532    32.09610
11533    32.49015
11535    27.70800
11536    25.95400
Name: Div, Length: 1396, dtype: float64

In [8]:
rs[rs['Div'] < 10].department.unique()

array(['Alpes_de_Haute_Provence', 'Alpes_Maritimes', 'Ardeche', 'Ariege',
       'Aude', 'Aveyron', 'Bouches_du_Rhone', 'Cantal', 'Correze',
       'Corse_du_Sud', 'Creuse', 'Dordogne', 'Doubs', 'Drome', 'Gard',
       'Gironde', 'Haut_Rhin', 'Haute_Corse', 'Haute_Loire',
       'Haute_Savoie', 'Haute_Vienne', 'Hautes_Alpes', 'Hautes_pyrenees',
       'Herault', 'Jura', 'Landes', 'Loire', 'Lot', 'Lozere',
       'Pyrenees_Atlantiques', 'Pyrenees_Orientales', 'Rhone', 'Savoie',
       'Seine_Saint_Denis', 'Tarn_et_Garonne', 'Territoire_de_Belfort',
       'Val_de_Marne', 'Var', 'Vaucluse', 'Vosges'], dtype=object)

In [12]:
rs[rs.department == "Ain"]

department  year  yield     area  production
103        Ain  2003    5.3  24021.0    127311.3
104        Ain  2004    8.0  28533.0    228264.0
105        Ain  2005    6.8  27039.0    183865.2
106        Ain  2006    7.2  31555.0    227196.0
107        Ain  2007    6.2  32065.0    198803.0
108        Ain  2008    6.3  32075.0    202072.5
109        Ain  2009    7.0  26620.0    186340.0
110        Ain  2010    7.2  33237.0    239306.4
111        Ain  2011    7.0  32300.0    226100.0
112        Ain  2012    6.7  34100.0    228470.0
113        Ain  2013    6.2  33680.0    208816.0
114        Ain  2014    7.2  29780.0    214416.0
115        Ain  2015    7.2  33600.0    241920.0
117        Ain  2017    7.4  32300.0    239020.0
118        Ain  2018    6.7  34650.0    232155.0

In [13]:
rs[rs.department == "Ain"].production

103    127311.3
104    228264.0
105    183865.2
106    227196.0
107    198803.0
108    202072.5
109    186340.0
110    239306.4
111    226100.0
112    228470.0
113    208816.0
114    214416.0
115    241920.0
117    239020.0
118    232155.0
Name: production, dtype: float64

In [23]:
a = dict()
a = a.fromkeys(['e', 'n'], dict.fromkeys([1, 2], 0))

In [26]:
a['e'][1]

0

In [14]:
rs[rs.department == "Ain"].year

103    2003
104    2004
105    2005
106    2006
107    2007
108    2008
109    2009
110    2010
111    2011
112    2012
113    2013
114    2014
115    2015
117    2017
118    2018
Name: year, dtype: int64

In [4]:
rs.to_csv("winter_wheat_filtered_2002.csv", index= False)

In [21]:
import numpy as np    
hist, bin_edges = np.histogram([-1, -1, 2, 2, 2, 2, 3], bins = range(-1,5))

In [22]:
hist

array([2, 0, 0, 4, 1])

In [23]:
bin_edges

array([-1,  0,  1,  2,  3,  4])

In [33]:
np.delete(np.bincount([1, 1, 2, 2, 2, 2, 3], minlength = 5), [0])

array([2, 4, 1, 0])

In [15]:
k.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [17]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]