In [1]:
import pandas as pd
import numpy as np

In [2]:
rs = pd.read_csv("2021-001_Schauberger-et-al_Data_FILTERED/wheat_winter_data_1900-2018_FILTERED.txt", index_col= False, sep = ";")

In [16]:
[[i] for i in (list(rs[rs.department == "Ain"].year))]

[[2003],
 [2004],
 [2005],
 [2006],
 [2007],
 [2008],
 [2009],
 [2010],
 [2011],
 [2012],
 [2013],
 [2014],
 [2015],
 [2017],
 [2018]]

In [7]:
rs['department'].unique()

array(['Ain', 'Aisne', 'Allier', 'Alpes_de_Haute_Provence',
       'Alpes_Maritimes', 'Ardeche', 'Ardennes', 'Ariege', 'Aube', 'Aude',
       'Aveyron', 'Bas_Rhin', 'Bouches_du_Rhone', 'Calvados', 'Cantal',
       'Charente', 'Charente_Maritime', 'Cher', 'Correze', 'Corse_du_Sud',
       'Cote_d_Or', 'Cotes_d_Armor', 'Creuse', 'Deux_Sevres', 'Dordogne',
       'Doubs', 'Drome', 'Essonne', 'Eure', 'Eure_et_Loir', 'Finistere',
       'Gard', 'Gers', 'Gironde', 'Haut_Rhin', 'Haute_Corse',
       'Haute_Garonne', 'Haute_Loire', 'Haute_Marne', 'Haute_Saone',
       'Haute_Savoie', 'Haute_Vienne', 'Hautes_Alpes', 'Hautes_pyrenees',
       'Hauts_de_Seine', 'Herault', 'Ille_et_Vilaine', 'Indre',
       'Indre_et_Loire', 'Isere', 'Jura', 'Landes', 'Loir_et_Cher',
       'Loire', 'Loire_Atlantique', 'Loiret', 'Lot', 'Lot_et_Garonne',
       'Lozere', 'Maine_et_Loire', 'Manche', 'Marne', 'Mayenne',
       'Meurthe_et_Moselle', 'Meuse', 'Morbihan', 'Moselle', 'Nievre',
       'Nord', 'Oise', 'Orn

In [3]:
rs = rs[rs['year'] > 2002]
rs = rs.dropna()

In [4]:
rs[rs.production < 1000]

department  year    yield   area  production
580        Alpes_Maritimes  2004  4.00000   65.0      260.00
581        Alpes_Maritimes  2005  4.00000   65.0      260.00
582        Alpes_Maritimes  2006  4.00000   15.0       60.00
583        Alpes_Maritimes  2007  3.50000   10.0       35.00
584        Alpes_Maritimes  2008  4.10000   15.0       61.50
585        Alpes_Maritimes  2009  4.10000    3.0       12.30
587        Alpes_Maritimes  2011  3.80000   14.0       53.20
588        Alpes_Maritimes  2012  4.00000   10.0       40.00
589        Alpes_Maritimes  2013  3.80000    8.0       30.40
590        Alpes_Maritimes  2014  4.00000    5.0       20.00
591        Alpes_Maritimes  2015  4.00000    8.0       32.00
592        Alpes_Maritimes  2016  4.20000    8.0       33.60
594        Alpes_Maritimes  2018  4.00000    9.0       36.00
1532      Bouches_du_Rhone  2004  3.20000  258.0      825.60
1533      Bouches_du_Rhone  2005  3.40000  277.0      941.80
2377          Corse_du_Sud  2016  3.00000    3.0        9.00
2378          Corse_du_Sud  2017  3.50000    3.0       10.50
2379          Corse_du_Sud  2018  3.50000    3.0       10.50
4268           Haute_Corse  2003  1.80000   92.0      165.60
4269           Haute_Corse  2004  3.50000  106.0      371.00
4270           Haute_Corse  2005  3.50000   74.0      259.00
4271           Haute_Corse  2006  3.50000   80.0      280.00
4272           Haute_Corse  2007  3.50000   99.0      346.50
4273           Haute_Corse  2008  3.00000  102.0      306.00
4274           Haute_Corse  2009  3.00000   70.0      210.00
4275           Haute_Corse  2010  3.00000   72.0      216.00
4276           Haute_Corse  2011  3.00000   80.0      240.00
4277           Haute_Corse  2012  3.50000   65.0      227.50
4278           Haute_Corse  2013  3.50000  120.0      420.00
4279           Haute_Corse  2014  3.50000  130.0      455.00
4280           Haute_Corse  2015  3.50000  105.0      367.50
4281           Haute_Corse  2016  3.00000   75.0      225.00
4282           Haute_Corse  2017  3.50000   70.0      245.00
4283           Haute_Corse  2018  3.50000   60.0      210.00
5461               Herault  2006  2.80000  330.0      924.00
9025   Pyrenees_Orientales  2003  2.50000  300.0      750.00
9026   Pyrenees_Orientales  2004  3.00000  300.0      900.00
9027   Pyrenees_Orientales  2005  2.00000  300.0      600.00
9028   Pyrenees_Orientales  2006  2.50000  300.0      750.00
9029   Pyrenees_Orientales  2007  2.10000  150.0      315.00
9030   Pyrenees_Orientales  2008  2.80000  180.0      504.00
9031   Pyrenees_Orientales  2009  2.80000  130.0      364.00
9032   Pyrenees_Orientales  2010  2.78571  140.0      390.00
9033   Pyrenees_Orientales  2011  3.00000  100.0      300.00
9034   Pyrenees_Orientales  2012  3.00000  150.0      450.00
9035   Pyrenees_Orientales  2013  4.00000  180.0      720.00
9036   Pyrenees_Orientales  2014  2.90000  250.0      725.00
9037   Pyrenees_Orientales  2015  3.00000  245.0      735.00
9038   Pyrenees_Orientales  2016  2.80000  155.0      434.00
9039   Pyrenees_Orientales  2017  4.30000  165.0      709.50
9040   Pyrenees_Orientales  2018  3.50000  145.0      507.50
10811                  Var  2007  3.50000  231.0      808.50
10812                  Var  2008  4.10000  236.0      967.60
10813                  Var  2009  3.80000  196.0      744.80
10814                  Var  2010  3.80000  225.0      855.00
10815                  Var  2011  3.60000  171.0      615.60
10816                  Var  2012  3.80000  253.0      961.40
10817                  Var  2013  3.80000  249.0      946.20
10822                  Var  2018  3.39000  264.0      894.96

In [12]:
rs[rs.department == "Ain"]

department  year  yield     area  production
103        Ain  2003    5.3  24021.0    127311.3
104        Ain  2004    8.0  28533.0    228264.0
105        Ain  2005    6.8  27039.0    183865.2
106        Ain  2006    7.2  31555.0    227196.0
107        Ain  2007    6.2  32065.0    198803.0
108        Ain  2008    6.3  32075.0    202072.5
109        Ain  2009    7.0  26620.0    186340.0
110        Ain  2010    7.2  33237.0    239306.4
111        Ain  2011    7.0  32300.0    226100.0
112        Ain  2012    6.7  34100.0    228470.0
113        Ain  2013    6.2  33680.0    208816.0
114        Ain  2014    7.2  29780.0    214416.0
115        Ain  2015    7.2  33600.0    241920.0
117        Ain  2017    7.4  32300.0    239020.0
118        Ain  2018    6.7  34650.0    232155.0

In [13]:
rs[rs.department == "Ain"].production

103    127311.3
104    228264.0
105    183865.2
106    227196.0
107    198803.0
108    202072.5
109    186340.0
110    239306.4
111    226100.0
112    228470.0
113    208816.0
114    214416.0
115    241920.0
117    239020.0
118    232155.0
Name: production, dtype: float64

In [23]:
a = dict()
a = a.fromkeys(['e', 'n'], dict.fromkeys([1, 2], 0))

In [26]:
a['e'][1]

0

In [14]:
rs[rs.department == "Ain"].year

103    2003
104    2004
105    2005
106    2006
107    2007
108    2008
109    2009
110    2010
111    2011
112    2012
113    2013
114    2014
115    2015
117    2017
118    2018
Name: year, dtype: int64

In [4]:
rs.to_csv("winter_wheat_filtered_2002.csv", index= False)

In [21]:
import numpy as np    
hist, bin_edges = np.histogram([-1, -1, 2, 2, 2, 2, 3], bins = range(-1,5))

In [22]:
hist

array([2, 0, 0, 4, 1])

In [23]:
bin_edges

array([-1,  0,  1,  2,  3,  4])

In [33]:
np.delete(np.bincount([1, 1, 2, 2, 2, 2, 3], minlength = 5), [0])

array([2, 4, 1, 0])

In [15]:
k.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [17]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]